### ISSUE TITLE
Calibration Config - Using relight without chrome ball in each image

### ISSUE THREAD

**Issue by MiB76** [cnr-isti-vclab/relight#67]
Hello, is it possible to use relight without a chrome ball in each image. I want to make one photo of the chrome ball in the center of the image and then replace the chromeval by he object that I want to photograph. The light direction and intensities will stay the same for each image.
In other words: How can I set up relight to work with a "dome" with 8 lights arranged in a circle, illuminating the object/chrome ball from a 45 angle, with same distance/angles between lights.
Many thanks!
Michael

**Comment by jacopomazzoni** [comment]
save lp file and load lp file

**Comment by MiB76** [comment]
Thank you very much for the prompt answer, jacopomazzoni  :)

**Comment by ponchio** [comment]
Alternatively, you might create the lp by hand, here is an example (you will have to change the order of the light directions.
Lp is a text file with the numer of lights in the first line (8 in your case) and each of the following lines specifies a filename (but in relight we just care about the order) x, y, z unit vector.

Here is an example starting from the right in anticlockwise order:
8
photo1.jpg 0.707106781 0 0.707106781
photo2.jpg 0,577350269 0,577350269 0,577350269
photo3.jpg 0 0.707106781 0.707106781
photo4.jpg -0,577350269 0,577350269 0,577350269
photo5.jpg -0.707106781 0 0.707106781
photo6.jpg -0,577350269 -0,577350269 0,577350269
photo7.jpg 0 -0.707106781 0.707106781
photo8.jpg 0,577350269 -0,577350269 0,577350269

You might also want to select Sphere Dome and specify the dome diameter, the witth of the photo in the Calibration -> Dome Geometry menu, this should remove most of the normal distortion due to the finite size of the dome.

**Comment by MiB76** [comment]
Thank you very much, ponchio! I´m just rebuilding most of my scanner, but will test your recommendations soon.
